# Description:
#   Integrations of other tools into the checkers unit test framework.

licenses(["notice"])  # Apache v2.0

exports_files(["LICENSE"])

py_library(
    name = "hamcrest",
    testonly = 1,
    srcs = ["hamcrest.py"],
    visibility = ["//visibility:public"],
    deps = ["//third_party/py/hamcrest"],
)
